
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.qgen.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 10;
  public static final int INTEGER = 14;
  public static final int COLON = 12;
  public static final int COUNT = 5;
  public static final int ANS = 6;
  public static final int BODY = 7;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int TITLE = 3;
  public static final int VAR = 13;
  public static final int TYPE = 4;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int DEF = 2;
  public static final int RBRACE = 11;
  public static final int LPAREN = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "TITLE",
  "TYPE",
  "COUNT",
  "ANS",
  "BODY",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COLON",
  "VAR",
  "INTEGER",
  "STRING"
  };
}

